spring.application.name=splittrip-api
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/splittrip}
spring.datasource.username=${DB_USERNAME:splittrip}
spring.datasource.password=${DB_PASSWORD:splittrip}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
